services:
  postgres-sf:
    container_name: sf-postgres
    image: postgres:11.4-alpine
    ports:
    - published: 5432
      target: 5432
    volumes:
    - /opt/data/sf_data/postgres:/var/lib/postgresql/data:rw
version: '3.9'

